/**
 * Paperclip Trading Plugin — Database Schema (Drizzle ORM)
 * =========================================================
 * Integrates with Paperclip's existing PostgreSQL via Drizzle.
 * All tables prefixed with `trading_` to avoid conflicts.
 */

import {
  pgTable,
  uuid,
  varchar,
  text,
  numeric,
  integer,
  boolean,
  timestamp,
  jsonb,
  date,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// ─── Assets ─────────────────────────────────────────────────
export const tradingAssets = pgTable(
  "trading_assets",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    symbol: varchar("symbol", { length: 20 }).notNull(),
    assetClass: varchar("asset_class", { length: 20 }).notNull(), // crypto, equity, forex, commodity
    exchange: varchar("exchange", { length: 50 }).notNull(),
    baseCurrency: varchar("base_currency", { length: 10 }),
    quoteCurrency: varchar("quote_currency", { length: 10 }),
    isActive: boolean("is_active").default(true),
    metadata: jsonb("metadata").default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    symbolExchangeIdx: uniqueIndex("trading_assets_symbol_exchange").on(table.symbol, table.exchange),
  })
);

// ─── Market Snapshots (written by Scanner Agents) ───────────
export const tradingSnapshots = pgTable(
  "trading_snapshots",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    assetId: uuid("asset_id").notNull().references(() => tradingAssets.id),
    timestamp: timestamp("timestamp", { withTimezone: true }).notNull(),
    price: numeric("price", { precision: 20, scale: 8 }).notNull(),
    volume24h: numeric("volume_24h", { precision: 20, scale: 2 }),
    priceChange1h: numeric("price_change_1h", { precision: 10, scale: 4 }),
    priceChange24h: numeric("price_change_24h", { precision: 10, scale: 4 }),
    priceChange7d: numeric("price_change_7d", { precision: 10, scale: 4 }),
    high24h: numeric("high_24h", { precision: 20, scale: 8 }),
    low24h: numeric("low_24h", { precision: 20, scale: 8 }),
    rsi14: numeric("rsi_14", { precision: 6, scale: 2 }),
    volumeRatio: numeric("volume_ratio", { precision: 10, scale: 4 }),
    fundingRate: numeric("funding_rate", { precision: 10, scale: 6 }),
    rawData: jsonb("raw_data").default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    assetTimeIdx: index("trading_snapshots_asset_time").on(table.assetId, table.timestamp),
    timestampIdx: index("trading_snapshots_timestamp").on(table.timestamp),
  })
);

// ─── Signals (detected by Scanner Agents) ───────────────────
export const tradingSignals = pgTable(
  "trading_signals",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    assetId: uuid("asset_id").notNull().references(() => tradingAssets.id),
    signalType: varchar("signal_type", { length: 50 }).notNull(),
    severity: varchar("severity", { length: 10 }), // low, medium, high, critical
    value: numeric("value", { precision: 20, scale: 8 }),
    context: jsonb("context").default({}),
    detectedAt: timestamp("detected_at", { withTimezone: true }).notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    isActive: boolean("is_active").default(true),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    activeIdx: index("trading_signals_active").on(table.isActive, table.detectedAt),
    typeIdx: index("trading_signals_type").on(table.signalType, table.detectedAt),
  })
);

// ─── Hypotheses (generated by Hypothesis Agents) ────────────
export const tradingHypotheses = pgTable(
  "trading_hypotheses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name", { length: 200 }).notNull(),
    description: text("description").notNull(),
    assetClass: varchar("asset_class", { length: 20 }).notNull(),
    strategyType: varchar("strategy_type", { length: 50 }).notNull(),
    entryRules: jsonb("entry_rules").notNull(),
    exitRules: jsonb("exit_rules").notNull(),
    riskParams: jsonb("risk_params").notNull().default({
      max_position_pct: 2,
      stop_loss_pct: 5,
      take_profit_pct: 10,
    }),
    status: varchar("status", { length: 20 }).default("draft"),
    confidence: numeric("confidence", { precision: 5, scale: 2 }).default("0"),
    generation: integer("generation").default(1),
    parentId: uuid("parent_id"),
    createdBy: varchar("created_by", { length: 50 }).default("hypothesis_agent"),
    promotedAt: timestamp("promoted_at", { withTimezone: true }),
    retiredAt: timestamp("retired_at", { withTimezone: true }),
    retirementReason: text("retirement_reason"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    statusIdx: index("trading_hypotheses_status").on(table.status),
    confidenceIdx: index("trading_hypotheses_confidence").on(table.confidence),
  })
);

// ─── Backtest Results ───────────────────────────────────────
export const tradingBacktestResults = pgTable(
  "trading_backtest_results",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    hypothesisId: uuid("hypothesis_id").notNull().references(() => tradingHypotheses.id),
    periodStart: date("period_start").notNull(),
    periodEnd: date("period_end").notNull(),
    totalTrades: integer("total_trades").notNull(),
    winningTrades: integer("winning_trades").notNull(),
    losingTrades: integer("losing_trades").notNull(),
    winRate: numeric("win_rate", { precision: 5, scale: 2 }),
    totalReturn: numeric("total_return", { precision: 10, scale: 4 }),
    sharpeRatio: numeric("sharpe_ratio", { precision: 8, scale: 4 }),
    maxDrawdown: numeric("max_drawdown", { precision: 10, scale: 4 }),
    avgTradeReturn: numeric("avg_trade_return", { precision: 10, scale: 6 }),
    profitFactor: numeric("profit_factor", { precision: 8, scale: 4 }),
    calmarRatio: numeric("calmar_ratio", { precision: 8, scale: 4 }),
    avgHoldHours: numeric("avg_hold_hours", { precision: 10, scale: 2 }),
    rawResults: jsonb("raw_results").default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    hypothesisIdx: index("trading_backtest_hypothesis").on(table.hypothesisId, table.createdAt),
  })
);

// ─── Paper Trades ───────────────────────────────────────────
export const tradingPaperTrades = pgTable(
  "trading_paper_trades",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    hypothesisId: uuid("hypothesis_id").notNull().references(() => tradingHypotheses.id),
    assetId: uuid("asset_id").notNull().references(() => tradingAssets.id),
    direction: varchar("direction", { length: 5 }).notNull(), // long, short
    entryPrice: numeric("entry_price", { precision: 20, scale: 8 }).notNull(),
    entryTime: timestamp("entry_time", { withTimezone: true }).notNull(),
    exitPrice: numeric("exit_price", { precision: 20, scale: 8 }),
    exitTime: timestamp("exit_time", { withTimezone: true }),
    quantity: numeric("quantity", { precision: 20, scale: 8 }).notNull(),
    pnl: numeric("pnl", { precision: 20, scale: 8 }),
    pnlPct: numeric("pnl_pct", { precision: 10, scale: 4 }),
    status: varchar("status", { length: 20 }).default("open"),
    entrySignalId: uuid("entry_signal_id"),
    exitReason: varchar("exit_reason", { length: 100 }),
    metadata: jsonb("metadata").default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    hypothesisIdx: index("trading_paper_hypothesis").on(table.hypothesisId, table.status),
  })
);

// ─── Meta-Agent Decisions ───────────────────────────────────
export const tradingMetaDecisions = pgTable(
  "trading_meta_decisions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    cycleNumber: integer("cycle_number").notNull(),
    cycleDate: date("cycle_date").notNull(),
    decisions: jsonb("decisions").notNull(),
    reasoning: text("reasoning").notNull(),
    performanceSummary: jsonb("performance_summary").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    cycleDateIdx: index("trading_meta_cycle_date").on(table.cycleDate),
  })
);

// ─── System Config ──────────────────────────────────────────
export const tradingConfig = pgTable("trading_config", {
  key: varchar("key", { length: 100 }).primaryKey(),
  value: jsonb("value").notNull(),
  description: text("description"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

// ─── Agent Logs ─────────────────────────────────────────────
export const tradingAgentLogs = pgTable(
  "trading_agent_logs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    agentName: varchar("agent_name", { length: 100 }).notNull(),
    logLevel: varchar("log_level", { length: 10 }).default("info"),
    message: text("message").notNull(),
    context: jsonb("context").default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    timeIdx: index("trading_agent_logs_time").on(table.createdAt),
    agentIdx: index("trading_agent_logs_agent").on(table.agentName, table.createdAt),
  })
);

// ─── Relations ──────────────────────────────────────────────
export const snapshotRelations = relations(tradingSnapshots, ({ one }) => ({
  asset: one(tradingAssets, {
    fields: [tradingSnapshots.assetId],
    references: [tradingAssets.id],
  }),
}));

export const signalRelations = relations(tradingSignals, ({ one }) => ({
  asset: one(tradingAssets, {
    fields: [tradingSignals.assetId],
    references: [tradingAssets.id],
  }),
}));

export const hypothesisRelations = relations(tradingHypotheses, ({ one, many }) => ({
  parent: one(tradingHypotheses, {
    fields: [tradingHypotheses.parentId],
    references: [tradingHypotheses.id],
  }),
  backtestResults: many(tradingBacktestResults),
  paperTrades: many(tradingPaperTrades),
}));

export const backtestRelations = relations(tradingBacktestResults, ({ one }) => ({
  hypothesis: one(tradingHypotheses, {
    fields: [tradingBacktestResults.hypothesisId],
    references: [tradingHypotheses.id],
  }),
}));
