/**
 * Orchestra schema — outcome-led orchestration layer.
 *
 * Five tables:
 *   - outcomes                    high-level user request ("create a market intel report")
 *   - orchestra_plans             versioned plan generated by the planner agent
 *   - orchestra_plan_steps        decomposed work units; each linked to an Issue once executing
 *   - orchestra_reviews           reviewer agent verdicts on completed steps
 *   - outcome_final_assemblies    the final synthesis stage (one per outcome)
 *
 * Existing Issue / IssueWorkProduct / HeartbeatRun / CostEvent rows do
 * the heavy lifting at execution time — orchestra layers on top.
 *
 * Status enums use text + the matching constants from @mattparrytfc/shared
 * are surfaced in zod validators rather than DB-level CHECKs, to keep
 * migrations cheap when we add a status. Indexes follow the pattern
 * (company_id), (outcome_id), (status), (created_at).
 */
import { sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  pgTable,
  uuid,
  text,
  timestamp,
  integer,
  jsonb,
  index,
  doublePrecision,
} from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { projects } from "./projects.js";
import { agents } from "./agents.js";
import { issues } from "./issues.js";
import { issueWorkProducts } from "./issue_work_products.js";

function sqlEmptyArray() {
  return sql`'[]'::jsonb`;
}

export const outcomes = pgTable(
  "outcomes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").references(() => projects.id, {
      onDelete: "set null",
    }),
    /** better-auth user id; null for system-created outcomes (e.g. via routine). */
    createdByUserId: text("created_by_user_id"),
    title: text("title").notNull(),
    brief: text("brief").notNull(),
    status: text("status").notNull().default("draft"),
    priority: text("priority").notNull().default("medium"),
    riskLevel: text("risk_level"),
    budgetLimitCents: integer("budget_limit_cents"),
    deadline: timestamp("deadline", { withTimezone: true }),
    targetFormat: text("target_format").notNull().default("report"),
    executionMode: text("execution_mode").notNull().default("review_plan_first"),
    /** Defaults to the company CEO if null at execution time. */
    orchestratorAgentId: uuid("orchestrator_agent_id").references(
      () => agents.id,
      { onDelete: "set null" },
    ),
    finalWorkProductId: uuid("final_work_product_id").references(
      () => issueWorkProducts.id,
      { onDelete: "set null" },
    ),
    metadata: jsonb("metadata"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    companyStatusIdx: index("outcomes_company_status_idx").on(
      t.companyId,
      t.status,
    ),
    companyCreatedIdx: index("outcomes_company_created_idx").on(
      t.companyId,
      t.createdAt,
    ),
    projectIdx: index("outcomes_project_idx").on(t.projectId),
  }),
);

export const orchestraPlans = pgTable(
  "orchestra_plans",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    outcomeId: uuid("outcome_id")
      .notNull()
      .references(() => outcomes.id, { onDelete: "cascade" }),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    /** Monotonic per-outcome version. */
    version: integer("version").notNull().default(1),
    status: text("status").notNull().default("draft"),
    summary: text("summary").notNull(),
    assumptions: jsonb("assumptions").notNull().default(sqlEmptyArray()),
    risks: jsonb("risks").notNull().default(sqlEmptyArray()),
    requiredInputs: jsonb("required_inputs").notNull().default(sqlEmptyArray()),
    estimatedCostCents: integer("estimated_cost_cents"),
    estimatedDurationMinutes: integer("estimated_duration_minutes"),
    confidenceScore: doublePrecision("confidence_score"),
    createdByAgentId: uuid("created_by_agent_id").references(() => agents.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    outcomeIdx: index("orchestra_plans_outcome_idx").on(t.outcomeId, t.version),
    statusIdx: index("orchestra_plans_status_idx").on(t.status),
    companyIdx: index("orchestra_plans_company_idx").on(t.companyId),
  }),
);

export const orchestraPlanSteps = pgTable(
  "orchestra_plan_steps",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    planId: uuid("plan_id")
      .notNull()
      .references(() => orchestraPlans.id, { onDelete: "cascade" }),
    outcomeId: uuid("outcome_id")
      .notNull()
      .references(() => outcomes.id, { onDelete: "cascade" }),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    parentStepId: uuid("parent_step_id").references(
      (): AnyPgColumn => orchestraPlanSteps.id,
      { onDelete: "set null" },
    ),
    /** Stable display order within the plan. */
    ordinal: integer("ordinal").notNull(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    stepType: text("step_type").notNull(),
    status: text("status").notNull().default("pending"),
    recommendedAgentId: uuid("recommended_agent_id").references(
      () => agents.id,
      { onDelete: "set null" },
    ),
    assignedAgentId: uuid("assigned_agent_id").references(() => agents.id, {
      onDelete: "set null",
    }),
    issueId: uuid("issue_id").references(() => issues.id, {
      onDelete: "set null",
    }),
    /** Array of step ids this step depends on. */
    dependsOnStepIds: jsonb("depends_on_step_ids")
      .notNull()
      .default(sqlEmptyArray()),
    acceptanceCriteria: jsonb("acceptance_criteria")
      .notNull()
      .default(sqlEmptyArray()),
    reviewCriteria: jsonb("review_criteria")
      .notNull()
      .default(sqlEmptyArray()),
    outputRequirement: text("output_requirement"),
    revisionCount: integer("revision_count").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    planOrdinalIdx: index("orchestra_plan_steps_plan_ordinal_idx").on(
      t.planId,
      t.ordinal,
    ),
    outcomeIdx: index("orchestra_plan_steps_outcome_idx").on(t.outcomeId),
    statusIdx: index("orchestra_plan_steps_status_idx").on(t.status),
    issueIdx: index("orchestra_plan_steps_issue_idx").on(t.issueId),
    assignedAgentIdx: index("orchestra_plan_steps_assigned_agent_idx").on(
      t.assignedAgentId,
    ),
  }),
);

export const orchestraReviews = pgTable(
  "orchestra_reviews",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    outcomeId: uuid("outcome_id")
      .notNull()
      .references(() => outcomes.id, { onDelete: "cascade" }),
    planId: uuid("plan_id")
      .notNull()
      .references(() => orchestraPlans.id, { onDelete: "cascade" }),
    stepId: uuid("step_id").references(() => orchestraPlanSteps.id, {
      onDelete: "cascade",
    }),
    reviewedWorkProductId: uuid("reviewed_work_product_id").references(
      () => issueWorkProducts.id,
      { onDelete: "set null" },
    ),
    reviewerAgentId: uuid("reviewer_agent_id")
      .notNull()
      .references(() => agents.id),
    status: text("status").notNull().default("pending"),
    score: integer("score"),
    comments: text("comments"),
    revisionInstructions: text("revision_instructions"),
    gaps: jsonb("gaps").notNull().default(sqlEmptyArray()),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    outcomeIdx: index("orchestra_reviews_outcome_idx").on(t.outcomeId),
    stepIdx: index("orchestra_reviews_step_idx").on(t.stepId),
    statusIdx: index("orchestra_reviews_status_idx").on(t.status),
  }),
);

export const outcomeFinalAssemblies = pgTable(
  "outcome_final_assemblies",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    outcomeId: uuid("outcome_id")
      .notNull()
      .references(() => outcomes.id, { onDelete: "cascade" }),
    planId: uuid("plan_id")
      .notNull()
      .references(() => orchestraPlans.id, { onDelete: "cascade" }),
    assemblerAgentId: uuid("assembler_agent_id")
      .notNull()
      .references(() => agents.id),
    status: text("status").notNull().default("pending"),
    sourceWorkProductIds: jsonb("source_work_product_ids")
      .notNull()
      .default(sqlEmptyArray()),
    structure: jsonb("structure"),
    finalMarkdown: text("final_markdown"),
    finalSummary: text("final_summary"),
    unresolvedLimitations: jsonb("unresolved_limitations")
      .notNull()
      .default(sqlEmptyArray()),
    recommendedNextActions: jsonb("recommended_next_actions")
      .notNull()
      .default(sqlEmptyArray()),
    finalWorkProductId: uuid("final_work_product_id").references(
      () => issueWorkProducts.id,
      { onDelete: "set null" },
    ),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    outcomeIdx: index("outcome_final_assemblies_outcome_idx").on(t.outcomeId),
    statusIdx: index("outcome_final_assemblies_status_idx").on(t.status),
  }),
);

