/**
 * Narrator service.
 *
 * Renders plain-English summaries of real system state for the UI's
 * narrative panels. The brief is explicit — *factual, concise,
 * non-hypey, transparent about uncertainty, never invents progress*.
 *
 * Two scopes:
 *   forCompany(companyId)  — what's happening across this company
 *   forOutcome(outcomeId)  — what's happening on this outcome
 *
 * Uses the same Anthropic bridge as the orchestra services, with a
 * 60-second per-key in-memory cache to keep cost low and the UI snappy.
 *
 * Fallback: if the LLM is unavailable (no key, low credits, transient
 * error) we return a *deterministic* factual sentence assembled from
 * the same state. We never invent narrative when we can't verify it.
 */
import { and, desc, eq } from "drizzle-orm";
import type { Db } from "@orqestra/db";
import {
  outcomes,
  orchestraPlans,
  orchestraPlanSteps,
  agents,
  approvals,
  heartbeatRuns,
} from "@orqestra/db";
import {
  defaultRunLLM,
  OrchestraLLMNotConfiguredError,
  type OrchestraRunLLM,
} from "./orchestra-llm.js";

export interface NarrativeResult {
  summary: string;
  /** ISO timestamp this narrative was generated. */
  generatedAt: string;
  /**
   * "llm" — generated by the model.
   * "fallback" — deterministic sentence assembled from facts (no LLM call landed).
   */
  source: "llm" | "fallback";
  /** Human-readable reason if source==="fallback". */
  fallbackReason?: string;
}

const NARRATOR_SYSTEM_PROMPT = `You are Orqestra's narrator. Your job is to translate real system state into one short, plain-English paragraph that a non-technical founder can read in five seconds.

Hard rules:
- BRITISH ENGLISH. "organise", "colour", "behaviour".
- Sentence case. No trailing periods on one-line summaries.
- Use the word "task", not "issue".
- Use "Route to" for delegation.
- NO marketing puff. NO motivational fluff. NO buzzwords.
- NEVER invent progress. NEVER pretend work has happened that has not.
- If the system is idle or has nothing to report, say so simply.
- If something is uncertain — say so honestly ("we don't yet have enough source material to be confident").
- Maximum two short sentences. Lead with what matters most right now. End with what happens next, IF anything is actually queued up.

You receive a JSON facts block. Use only those facts. Do not infer beyond them.`;

const COMPANY_TTL_MS = 30_000;
const OUTCOME_TTL_MS = 30_000;

interface CacheEntry {
  value: NarrativeResult;
  expiresAt: number;
}

interface NarratorDeps {
  runLLM?: OrchestraRunLLM;
  /** Override the cache TTL for tests. */
  ttlMs?: number;
}

export function narratorService(db: Db, deps: NarratorDeps = {}) {
  const runLLM = deps.runLLM ?? defaultRunLLM;
  const cache = new Map<string, CacheEntry>();

  async function gatherCompanyFacts(companyId: string) {
    const allOutcomes = await db
      .select({
        id: outcomes.id,
        title: outcomes.title,
        status: outcomes.status,
      })
      .from(outcomes)
      .where(eq(outcomes.companyId, companyId));

    const activeOutcomes = allOutcomes.filter(
      (o) =>
        o.status !== "delivered" &&
        o.status !== "cancelled" &&
        o.status !== "failed",
    );
    const blockedOutcomes = allOutcomes.filter(
      (o) =>
        o.status === "awaiting_clarification" || o.status === "failed",
    );
    const deliveredOutcomes = allOutcomes.filter(
      (o) => o.status === "delivered",
    );

    const pendingApprovalRows = await db
      .select({ id: approvals.id })
      .from(approvals)
      .where(
        and(
          eq(approvals.companyId, companyId),
          eq(approvals.status, "pending"),
        ),
      );

    const agentRows = await db
      .select({
        id: agents.id,
        name: agents.name,
        status: agents.status,
      })
      .from(agents)
      .where(eq(agents.companyId, companyId));

    const activeAgents = agentRows.filter((a) => a.status === "active").length;
    const erroredAgents = agentRows.filter((a) => a.status === "error").length;

    const runningRunRows = await db
      .select({
        id: heartbeatRuns.id,
        agentId: heartbeatRuns.agentId,
      })
      .from(heartbeatRuns)
      .where(
        and(
          eq(heartbeatRuns.companyId, companyId),
          eq(heartbeatRuns.status, "running"),
        ),
      );

    return {
      totalOutcomes: allOutcomes.length,
      activeOutcomeTitles: activeOutcomes.slice(0, 5).map((o) => o.title),
      activeOutcomeCount: activeOutcomes.length,
      blockedOutcomeCount: blockedOutcomes.length,
      deliveredOutcomeCount: deliveredOutcomes.length,
      pendingApprovalCount: pendingApprovalRows.length,
      totalAgents: agentRows.length,
      activeAgents,
      erroredAgents,
      runningRunCount: runningRunRows.length,
    };
  }

  async function gatherOutcomeFacts(outcomeId: string) {
    const [outcomeRow] = await db
      .select()
      .from(outcomes)
      .where(eq(outcomes.id, outcomeId));
    if (!outcomeRow) {
      return null;
    }

    const [latestPlan] = await db
      .select()
      .from(orchestraPlans)
      .where(eq(orchestraPlans.outcomeId, outcomeId))
      .orderBy(desc(orchestraPlans.version))
      .limit(1);

    const stepRows = latestPlan
      ? await db
          .select()
          .from(orchestraPlanSteps)
          .where(eq(orchestraPlanSteps.planId, latestPlan.id))
      : [];

    const completedSteps = stepRows.filter(
      (s) => s.status === "completed",
    ).length;
    const runningStep = stepRows.find((s) => s.status === "running");
    const blockedStep = stepRows.find((s) => s.status === "blocked");
    const failedStep = stepRows.find((s) => s.status === "failed");
    const requiredInputs = ((latestPlan?.requiredInputs ?? []) as Array<{
      question: string;
      required?: boolean;
    }>);

    return {
      title: outcomeRow.title,
      status: outcomeRow.status,
      hasPlan: !!latestPlan,
      summary: latestPlan?.summary ?? null,
      stepsTotal: stepRows.length,
      stepsCompleted: completedSteps,
      runningStepTitle: runningStep?.title ?? null,
      blockedStepTitle: blockedStep?.title ?? null,
      failedStepTitle: failedStep?.title ?? null,
      requiresClarification:
        outcomeRow.status === "awaiting_clarification" &&
        requiredInputs.length > 0,
      missingInputs: requiredInputs
        .filter((m) => m.required)
        .map((m) => m.question)
        .slice(0, 3),
    };
  }

  return {
    forCompany: async (companyId: string): Promise<NarrativeResult> => {
      const ttlMs = deps.ttlMs ?? COMPANY_TTL_MS;
      const key = `c:${companyId}`;
      const hit = cache.get(key);
      if (hit && hit.expiresAt > Date.now()) return hit.value;

      const facts = await gatherCompanyFacts(companyId);
      const prompt = `Render a one- or two-sentence plain-English narrative for this company's current state.\n\nFacts (JSON):\n${JSON.stringify(facts, null, 2)}\n\nFocus on what the operator should know in five seconds. If there is nothing in flight, say "Nothing in flight" plainly.`;

      try {
        const { text } = await runLLM({
          systemPrompt: NARRATOR_SYSTEM_PROMPT,
          prompt,
          maxOutputTokens: 300,
        });
        const value: NarrativeResult = {
          summary: text.trim(),
          generatedAt: new Date().toISOString(),
          source: "llm",
        };
        cache.set(key, { value, expiresAt: Date.now() + ttlMs });
        return value;
      } catch (err) {
        const fallback = companyFallback(facts);
        return {
          summary: fallback,
          generatedAt: new Date().toISOString(),
          source: "fallback",
          fallbackReason: explainErr(err),
        };
      }
    },

    forOutcome: async (outcomeId: string): Promise<NarrativeResult | null> => {
      const ttlMs = deps.ttlMs ?? OUTCOME_TTL_MS;
      const key = `o:${outcomeId}`;
      const hit = cache.get(key);
      if (hit && hit.expiresAt > Date.now()) return hit.value;

      const facts = await gatherOutcomeFacts(outcomeId);
      if (!facts) return null;

      const prompt = `Render a one- or two-sentence plain-English narrative for this outcome's current state.\n\nFacts (JSON):\n${JSON.stringify(facts, null, 2)}\n\nFocus on: what we are doing right now, and what changes once the current step finishes. If we are blocked or waiting, say so plainly. Do not pad.`;

      try {
        const { text } = await runLLM({
          systemPrompt: NARRATOR_SYSTEM_PROMPT,
          prompt,
          maxOutputTokens: 300,
        });
        const value: NarrativeResult = {
          summary: text.trim(),
          generatedAt: new Date().toISOString(),
          source: "llm",
        };
        cache.set(key, { value, expiresAt: Date.now() + ttlMs });
        return value;
      } catch (err) {
        const fallback = outcomeFallback(facts);
        return {
          summary: fallback,
          generatedAt: new Date().toISOString(),
          source: "fallback",
          fallbackReason: explainErr(err),
        };
      }
    },

    /** Test helper: clear the cache. */
    clearCache: () => cache.clear(),
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Deterministic fallback renderers — used when the LLM is unavailable.
// Honest. Factual. No invented progress.
// ─────────────────────────────────────────────────────────────────────────

interface CompanyFallbackFacts {
  activeOutcomeCount: number;
  blockedOutcomeCount: number;
  pendingApprovalCount: number;
  runningRunCount: number;
  erroredAgents: number;
}

function companyFallback(facts: CompanyFallbackFacts): string {
  const parts: string[] = [];
  if (facts.activeOutcomeCount === 0 && facts.runningRunCount === 0) {
    parts.push("Nothing in flight");
  } else {
    if (facts.runningRunCount > 0) {
      parts.push(
        `${facts.runningRunCount} agent run${facts.runningRunCount === 1 ? "" : "s"} in progress`,
      );
    }
    if (facts.activeOutcomeCount > 0) {
      parts.push(
        `${facts.activeOutcomeCount} active outcome${facts.activeOutcomeCount === 1 ? "" : "s"}`,
      );
    }
  }
  if (facts.blockedOutcomeCount > 0) {
    parts.push(`${facts.blockedOutcomeCount} waiting on you`);
  }
  if (facts.pendingApprovalCount > 0) {
    parts.push(
      `${facts.pendingApprovalCount} decision${facts.pendingApprovalCount === 1 ? "" : "s"} pending`,
    );
  }
  if (facts.erroredAgents > 0) {
    parts.push(
      `${facts.erroredAgents} agent${facts.erroredAgents === 1 ? "" : "s"} in error`,
    );
  }
  return parts.join(". ");
}

function outcomeFallback(facts: {
  status: string;
  stepsTotal: number;
  stepsCompleted: number;
  runningStepTitle: string | null;
  blockedStepTitle: string | null;
  failedStepTitle: string | null;
  requiresClarification: boolean;
}): string {
  if (facts.failedStepTitle)
    return `A step failed: ${facts.failedStepTitle}. Review needed before this can continue`;
  if (facts.blockedStepTitle)
    return `Blocked on: ${facts.blockedStepTitle}`;
  if (facts.requiresClarification)
    return `The planner needs your input before this can continue`;
  if (facts.runningStepTitle) {
    if (facts.stepsTotal > 0) {
      return `Working on: ${facts.runningStepTitle}. ${facts.stepsCompleted} of ${facts.stepsTotal} steps complete`;
    }
    return `Working on: ${facts.runningStepTitle}`;
  }
  if (facts.status === "delivered") return "Delivered";
  if (facts.status === "ready_to_execute")
    return "Plan drafted. Review and approve to start";
  if (facts.status === "draft") return "No plan yet";
  if (facts.status === "planning") return "Drafting the plan";
  if (facts.status === "assembling") return "Assembling the final deliverable";
  if (facts.status === "reviewing") return "Reviewing the latest work";
  if (facts.status === "cancelled") return "Cancelled";
  return `Status: ${facts.status}`;
}

function explainErr(err: unknown): string {
  if (err instanceof OrchestraLLMNotConfiguredError) {
    return "LLM not configured (ANTHROPIC_API_KEY missing)";
  }
  if (err instanceof Error) {
    if (/credit balance/i.test(err.message))
      return "Anthropic account is out of credits";
    return err.message.slice(0, 200);
  }
  return "Narrator LLM call failed";
}
